# start from base
FROM gcc:8
MAINTAINER Andrey Filimonov <andrey.v.filimonov@gmail.com>

# install system-wide deps
RUN apt-get -yqq update && \
  apt-get install -y git g++ libboost-all-dev libtool make pkg-config default-libmysqlclient-dev libssl-dev &&\
  apt-get install -y autoconf automake ragel bison flex virtualenv

RUN apt-get -yqq install libboost-program-options-dev
WORKDIR /src

# start app
CMD aclocal && automake && ./configure --disable-lua-records && make clean && make -j$(nproc)
